language: java
before_install: cd scouting486
deploy:
  provider: releases
  api-key: "$GithubOauthToken"
  file: "/home/travis/build/positronictraining/ScoutingApp/scouting486/target/scouting486-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
